[package]
name = "conways"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sdl2 = { version = "0.35", features = ["image", "ttf", "mixer"] }
rand = "0.8"
